# Generated by Django 5.2 on 2025-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('director', 'Director'), ('teacher', 'Teacher'), ('manager', 'Manager')], null=True),
        ),
    ]
