# Generated by Django 5.2 on 2025-07-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
